### ALL AUTHORS

GET http://rest_api.build/api/authors

### SINGLE AUTHOR
GET http://rest_api.build/api/authors/3

### ALL BOOKS
GET http://rest_api.build/api/books

### FIRST POST REQUEST
POST http://rest_api.build/api/authors
Accept: */*
Content-Type: application/json

{
    "name": "John Doe",
    "title": "Construction Worker",
    "company": "ABC Construction",
    "email": "constructor@email.com"
}